# Site settings
title: Felipe Sabino
email: felipe@sabino.me
author: Felipe Sabino
description: "Felipe Sabino's Page"
baseurl: ""
url: "http://felipe.sabino.me"
google_analytics: UA-22906860-2

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
